### ISSUE TITLE
启动崩溃

### ISSUE THREAD

**Issue by NortonAhu** [fire3/sailorcast#3]
`06-03 11:27:56.807 3241-3241/com.crixmod.sailorcast E/dalvikvm: Could not find class 'android.os.PersistableBundle', referenced from method com.crixmod.sailorcast.view.LauncherActivity.access$super
06-03 11:27:56.808 3241-3241/com.crixmod.sailorcast E/dalvikvm: Could not find class 'android.os.PersistableBundle', referenced from method com.crixmod.sailorcast.view.LauncherActivity.access$super
06-03 11:27:56.808 3241-3241/com.crixmod.sailorcast E/dalvikvm: Could not find class 'android.media.session.MediaController', referenced from method com.crixmod.sailorcast.view.LauncherActivity.access$super
06-03 11:27:56.808 3241-3241/com.crixmod.sailorcast E/dalvikvm: Could not find class 'android.widget.Toolbar', referenced from method com.crixmod.sailorcast.view.LauncherActivity.access$super
06-03 11:27:56.811 3241-3241/com.crixmod.sailorcast E/dalvikvm: Could not find class 'android.app.ActivityManager$TaskDescription', referenced from method com.crixmod.sailorcast.view.LauncherActivity.access$super
06-03 11:27:56.813 3241-3241/com.crixmod.sailorcast E/dalvikvm: Could not find class 'android.app.SharedElementCallback', referenced from method com.crixmod.sailorcast.view.LauncherActivity.access$super
06-03 11:27:56.813 3241-3241/com.crixmod.sailorcast E/dalvikvm: Could not find class 'android.os.PersistableBundle', referenced from method com.crixmod.sailorcast.view.LauncherActivity.access$super
06-03 11:27:56.819 3241-3241/com.crixmod.sailorcast E/dalvikvm: Could not find class 'android.app.SharedElementCallback', referenced from method com.crixmod.sailorcast.view.LauncherActivity.access$super
06-03 11:27:56.825 3241-3241/com.crixmod.sailorcast E/dalvikvm: Could not find class 'android.app.assist.AssistContent', referenced from method com.crixmod.sailorcast.view.LauncherActivity.access$super
06-03 11:27:56.826 3241-3241/com.crixmod.sailorcast E/dalvikvm: Could not find class 'android.view.SearchEvent', referenced from method com.crixmod.sailorcast.view.LauncherActivity.access$super
06-03 11:27:56.828 3241-3241/com.crixmod.sailorcast E/dalvikvm: Could not find class 'android.os.PersistableBundle', referenced from method com.crixmod.sailorcast.view.LauncherActivity.access$super
06-03 11:27:56.833 3241-3241/com.crixmod.sailorcast E/dalvikvm: Could not find class 'android.os.PersistableBundle', referenced from method com.crixmod.sailorcast.uiutils.BaseToolbarActivity.access$super
06-03 11:27:56.834 3241-3241/com.crixmod.sailorcast E/dalvikvm: Could not find class 'android.os.PersistableBundle', referenced from method com.crixmod.sailorcast.uiutils.BaseToolbarActivity.access$super
06-03 11:27:56.834 3241-3241/com.crixmod.sailorcast E/dalvikvm: Could not find class 'android.media.session.MediaController', referenced from method com.crixmod.sailorcast.uiutils.BaseToolbarActivity.access$super
06-03 11:27:56.834 3241-3241/com.crixmod.sailorcast E/dalvikvm: Could not find class 'android.widget.Toolbar', referenced from method com.crixmod.sailorcast.uiutils.BaseToolbarActivity.access$super
06-03 11:27:56.844 3241-3241/com.crixmod.sailorcast E/dalvikvm: Could not find class 'android.app.ActivityManager$TaskDescription', referenced from method com.crixmod.sailorcast.uiutils.BaseToolbarActivity.access$super
06-03 11:27:56.845 3241-3241/com.crixmod.sailorcast E/dalvikvm: Could not find class 'android.app.SharedElementCallback', referenced from method com.crixmod.sailorcast.uiutils.BaseToolbarActivity.access$super
06-03 11:27:56.846 3241-3241/com.crixmod.sailorcast E/dalvikvm: Could not find class 'android.os.PersistableBundle', referenced from method com.crixmod.sailorcast.uiutils.BaseToolbarActivity.access$super
06-03 11:27:56.847 3241-3241/com.crixmod.sailorcast E/dalvikvm: Could not find class 'android.app.SharedElementCallback', referenced from method com.crixmod.sailorcast.uiutils.BaseToolbarActivity.access$super
06-03 11:27:56.851 3241-3241/com.crixmod.sailorcast E/dalvikvm: Could not find class 'android.app.assist.AssistContent', referenced from method com.crixmod.sailorcast.uiutils.BaseToolbarActivity.access$super
06-03 11:27:56.852 3241-3241/com.crixmod.sailorcast E/dalvikvm: Could not find class 'android.view.SearchEvent', referenced from method com.crixmod.sailorcast.uiutils.BaseToolbarActivity.access$super
06-03 11:27:56.853 3241-3241/com.crixmod.sailorcast E/dalvikvm: Could not find class 'android.os.PersistableBundle', referenced from method com.crixmod.sailorcast.uiutils.BaseToolbarActivity.access$super
06-03 11:27:56.889 3241-3241/com.crixmod.sailorcast E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: com.crixmod.sailorcast, PID: 3241
                                                                      java.lang.RuntimeException: Unable to start activity ComponentInfo{com.crixmod.sailorcast/com.crixmod.sailorcast.view.LauncherActivity}: java.lang.IllegalArgumentException: AppCompat does not support the current theme features: { windowActionBar: false, windowActionBarOverlay: false, android:windowIsFloating: false, windowActionModeOverlay: true, windowNoTitle: false }
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2196)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
                                                                          at android.app.ActivityThread.access$800(ActivityThread.java:139)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1208)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:136)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5026)
                                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:515)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:802)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
                                                                          at dalvik.system.NativeStart.main(Native Method)
                                                                       Caused by: java.lang.IllegalArgumentException: AppCompat does not support the current theme features: { windowActionBar: false, windowActionBarOverlay: false, android:windowIsFloating: false, windowActionModeOverlay: true, windowNoTitle: false }
                                                                          at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java:458)
                                                                          at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:312)
                                                                          at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:277)
                                                                          at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                                          at com.crixmod.sailorcast.uiutils.BaseToolbarActivity.onCreate(BaseToolbarActivity.java:34)
                                                                          at com.crixmod.sailorcast.view.LauncherActivity.onCreate(LauncherActivity.java:24)
                                                                          at android.app.Activity.performCreate(Activity.java:5245)
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2160)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) 
                                                                          at android.app.ActivityThread.access$800(ActivityThread.java:139) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1208) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:136) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5026) 
                                                                          at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                          at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:802) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618) 
                                                                          at dalvik.system.NativeStart.main(Native Method) 
`

**Comment by fire3** [comment]
能不能说明一下测试环境？ android version ? API level ? 谢谢！

**Comment by NortonAhu** [comment]
不好意思 上午手快了，我用的是小米pad 4.4.4 版本

**Comment by fire3** [comment]
自己编译的？ 我自己编译了一下，然后在X86模拟器上运行倒是可以打开主界面，暂时没办法复现这个现场。

另外，软件本身对X86支持的并不好，原因如下：
1.  用了优酷一个从官方apk里面提取出来的解密动态库，是arm版本的，所以优酷本身播放链接在X86平台的安卓系统里是无法获取的。如果支持X86，可能要重写这部分代码。
2.  播放器暂时用的baidu的，也没有放支持x86的动态库。后续考虑替换成ijkplayer或exoplayer。
